---

# Install
# bspwm
# ansible
# python3 and pip
# thunderbird (inc. configration)

- name: Ensure that the system is up to date
  ansible.builtin.dnf:
    name: '*'
    state: latest
    update_cache: yes

- name: Enable RPM Fusion Repository Free
  ansible.builtin.dnf:
    name: "https://download1.rpmfusion.org/free/fedora/rpmfusion-free-release-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present
    disable_gpg_check: true
  when: ansible_distribution == "Fedora"

- name: Enable RPM Fusion Repository Non-Free
  ansible.builtin.dnf:
      name: "https://download1.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-{{ ansible_distribution_major_version }}.noarch.rpm"
      state: present
      disable_gpg_check: true
  when: ansible_distribution == "Fedora"

- name: Install defined packages
  ansible.builtin.dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ dnf_packages }}"

- name: Install proprietary/non-packaged software
  ansible.builtin.include_tasks: proprietary.yml

- name: Install OSS software
  ansible.builtin.include_tasks: oss.yml