---

- name: Create temporary working directory
  ansible.builtin.file:
    path: /tmp/ansible
    state: directory

# rmlint https://github.com/sahib/rmlint

- name: Check if rmlint is installed
  ansible.builtin.stat:
    path: /usr/bin/rmlint
  register: rmlint_installed

- name: Install rmlint
  block:
    - name: Install dependencies
      ansible.builtin.yum:
        name: "{{ item }}"
        state: present
      loop:
        - scons
        - python3-sphinx
        - gettext
        - json-glib-devel
        - glib2-devel
        - libblkid-devel
        - elfutils-libelf-devel
        - gtk3
        - librsvg2

    - name: Clone rmlint
      ansible.builtin.git:
        repo: https://github.com/sahib/rmlint.git
        dest: /tmp/ansible/rmlint

    - name: Build rmlint
      ansible.builtin.command: scons --prefix=/usr install
      args:
        chdir: /tmp/ansible/rmlint
  when: not rmlint_installed.stat.exists

# dust https://github.com/bootandy/dust

- name: Check if dust is installed
  ansible.builtin.stat:
    path: /usr/local/bin/dust
  register: dust_installed

- name: Install dust
  block:
    - name: Get latest dust release
      ansible.builtin.uri:
        url: https://api.github.com/repos/bootandy/dust/releases/latest
        return_content: yes
        status_code: 200
      register: dust_release

    - name: Download linux binary
      ansible.builtin.unarchive:
        remote_src: yes
        src: "{{ item.browser_download_url }}"
        dest: /tmp/ansible
      when: "'x86_64-unknown-linux-gnu.tar.gz' in item.name"
      loop: "{{ dust_release.json.assets }}"

    - name: Find dust directory name
      ansible.builtin.find:
          paths: /tmp/ansible
          recurse: yes
          file_type: directory
          patterns: dust*
      register: dust_folder

    - name: Move dust to /usr/local/bin
      ansible.builtin.copy:
        src: "{{ dust_folder.files[0].path }}/dust"
        dest: /usr/local/bin/dust
        mode: 0755
  when: dust_installed.stat.exists == False

# difftastic https://github.com/Wilfred/difftastic
- name: Check if brew is installed
  ansible.builtin.stat:
    path: /home/linuxbrew/.linuxbrew/bin/brew
  register: brew_installed

- name: Fail if brew is not installed
  ansible.builtin.fail:
    msg: "Brew is not installed, please install them manually"
  when: brew_installed.stat.exists == False

- name: Check if difftastic is installed
  ansible.builtin.stat:
      path: /home/linuxbrew/.linuxbrew/bin/difftastic
  register: difftastic_installed

- name: Install difftastic
  community.general.homebrew:
    name: difftastic
    state: present
  when: difftastic_installed.stat.exists == False
  become: yes
  become_user: "{{ user }}"

# git-split-diffs https://github.com/banga/git-split-diffs
- name: Check if git-split-diffs is installed
  ansible.builtin.stat:
    path: /usr/local/bin/git-split-diffs
  register: git_split_diffs_installed

- name: Install git-split-diffs
  ansible.builtin.command: npm install -g git-split-diffs
  when: git_split_diffs_installed.stat.exists == False

- name: Run git config
  ansible.builtin.command: git config --global core.pager "git-split-diffs --color | less -RFX"

# autorandr https://github.com/phillipberndt/autorandr
- name: Check if autorandr is installed
  ansible.builtin.stat:
    path: /usr/bin/autorandr
  register: autorandr_installed

- name: Install autorandr
  block:
    - name: Clone autorandr repository
      ansible.builtin.git:
        repo: https://github.com/phillipberndt/autorandr.git
        dest: /tmp/ansible/autorandr
        version: master

    - name: Install autorandr
      ansible.builtin.command: make install
      args:
        chdir: /tmp/ansible/autorandr

    - name: Remove autorandr repository
      ansible.builtin.file:
        path: /tmp/ansible/autorandr
        state: absent
  when: not autorandr_installed.stat.exists


# App image launcher https://github.com/TheAssassin/AppImageLauncher/releases/tag/v2.2.0
- name: Check if appimage launcher is installed
  ansible.builtin.stat:
    path: /usr/bin/appimagelauncherd
  register: appimage_launcher_installed

- name: Install appimage launcher
  block:
    - name: Get release information
      ansible.builtin.uri:
          url: https://api.github.com/repos/TheAssassin/AppImageLauncher/releases/latest
          return_content: yes
          status_code: 200
      register: appimage_launcher_release

    - name: Download rpm file
      ansible.builtin.get_url:
          url: "{{ item.browser_download_url }}"
          dest: /tmp/ansible/appimage-launcher.rpm
      when: "'x86_64.rpm' in item.name"
      loop: "{{ appimage_launcher_release.json.assets }}"

    - name: Install appimage launcher
      ansible.builtin.yum:
        name: /tmp/ansible/appimage-launcher.rpm
        state: present
        disable_gpg_check: yes
  when: not appimage_launcher_installed.stat.exists

# Musikcube
- name: Check if musikcube is installed
  ansible.builtin.stat:
    path: /usr/bin/musikcube
  register: musikcube_installed

- name: Install musikcube
  block:
    - name: Get GitHub release information
      ansible.builtin.uri:
          url: https://api.github.com/repos/clangen/musikcube/releases/latest
          return_content: yes
          status_code: 200
      register: musikcube_release

    - name: Download rpm
      ansible.builtin.get_url:
          url: "{{ item.browser_download_url }}"
          dest: /tmp/ansible/musikcube.rpm
      when: "'amd64.rpm' in item.name"
      loop: "{{ musikcube_release.json.assets }}"

    - name: Install musikcube
      ansible.builtin.yum:
        name: /tmp/ansible/musikcube.rpm
        state: present
        disable_gpg_check: yes

  when: not musikcube_installed.stat.exists

# Obsidian

- name: Check if obsidian is installed
  ansible.builtin.find:
    paths: "/home/{{ user }}/Applications"
    recurse: yes
    patterns: "Obsidian*"
  register: obsidian_installed

- name: Install obsidian
  block:
    - name: Get latest obsidian release
      ansible.builtin.uri:
        url: https://api.github.com/repos/obsidianmd/obsidian-releases/releases/latest
        return_content: yes
        status_code: 200
      register: obsidian_release

    - name: Download linux binary
      ansible.builtin.get_url:
        url: "{{ item.browser_download_url }}"
        dest: /tmp/ansible/
      when: "'.AppImage' in item.name and 'arm64' not in item.name"
      loop: "{{ obsidian_release.json.assets }}"

    - name: Find obsidian file
      ansible.builtin.find:
        paths: /tmp/ansible
        recurse: yes
        patterns: "Obsidian*"
      register: obsidian_file

    - name: Integrate obsidian
      ansible.builtin.command: "ail-cli integrate {{ obsidian_file.files[0].path }}"
      become: yes
      become_user: "{{ user }}"
  when: obsidian_installed.files|length == 0

# Logseq
- name: Check if Logseq is installed
  ansible.builtin.find:
      paths: "/home/{{ user }}/Applications"
      recurse: yes
      patterns: "Logseq*"
  register: logseq_installed

- name: Install logseq
  block:
    - name: Get release information
      ansible.builtin.uri:
          url: https://api.github.com/repos/logseq/logseq/releases/latest
          return_content: yes
          status_code: 200
      register: logseq_release

    - name: Download linux binary
      ansible.builtin.get_url:
          url: "{{ item.browser_download_url }}"
          dest: /tmp/ansible/
      when: "'.AppImage' in item.name and 'x64' in item.name"
      loop: "{{ logseq_release.json.assets }}"

    - name: Find logseq file
      ansible.builtin.find:
        paths: /tmp/ansible
        recurse: yes
        patterns: "Logseq*"
      register: logseq_file

    - name: Integrate logseq
      ansible.builtin.command: "ail-cli integrate {{ logseq_file.files[0].path }}"
      become: yes
      become_user: "{{ user }}"

  when: logseq_installed.files|length == 0

# Nerd fonts
- name: Check if nerd fonts is installed
  ansible.builtin.stat:
    path: "/home/{{ user }}/.local/share/fonts/NerdFonts"
  register: nerd_fonts_installed

- name: Install nerd fonts
  block:
    - name: Clone nerd fonts repository
      ansible.builtin.git:
        repo: https://github.com/ryanoasis/nerd-fonts.git
        dest: /tmp/ansible/nerd-fonts

    - name : Install nerd fonts
      ansible.builtin.command: ./install.sh
      args:
        chdir: /tmp/ansible/nerd-fonts
      become: yes
      become_user: "{{ user }}"

  when: not nerd_fonts_installed.stat.exists

# End
- name: Remove temporary working directory
  ansible.builtin.file:
    path: /tmp/ansible
    state: absent