---

- name: Allow user to sudo without password
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    state: present
    line: "{{ user }} ALL=(ALL) NOPASSWD: ALL"
  when: sudo_nopassword

- name: Add line in /etc/pulse/default.pa
  ansible.builtin.lineinfile:
    path: /etc/pulse/default.pa
    state: present
    line: "load-module module-switch-on-connect"


#- name: Get dotfile
#  ansible.builtin.git:
#      repo: https://github.com/UnciaBit/dotfiles
#      dest: /tmp/ansible/dotfiles
#
#- name: Copy dotfiles
#  ansible.builtin.copy:
#    src: /tmp/ansible/dotfiles/
#    dest: /home/{{ user }}/
#    owner: "{{ user }}"
#    group: "{{ user }}"
#    mode: 0644


# Fstab cusotm location + uid=1000,gid=1000 for user
# Transfer /etc/X11/xorg.conf.d/* files

# ibus japanese input
