name: Ansible Lint
on: [push, pull_request]

jobs:
  build:
    runs-on: fedora-36

    steps:
      - uses: actions/checkout@v2

      - name: Run ansible-lint
        # replace `main` with any valid ref, or tags like `v6`
        uses: ansible-community/ansible-lint-action@main
